"use strict";

/**
 * PRD template generator. `init` writes this to PRD.md.
 * Built to pass the rubric when filled in, and to teach Solana-specific thinking.
 */
const BASE_TEMPLATE = `# <Project Name> — PRD

> Solana / Web3 Product Requirements Document. Generated by SolPRD.
> Replace every <placeholder>. Run \`solprd audit\` to score it.

## Problem & Users

**Problem:** <What concrete problem are we solving? 2-3 sentences.>

**Target users / personas:** <e.g. retail traders, validators, dApp developers>

**Job to be done:** <As a <user>, I want <outcome> so that <benefit>.>

## Solution Overview & Scope

**Solution:** <One-paragraph description of the product.>

**In scope (features / deliverables):**
- <feature 1>
- <feature 2>

**Out of scope / Non-goals:**
- <thing we are explicitly NOT building in v1>

## On-chain Architecture

**Programs:** <Anchor or native? List program(s) and key instructions.>

**Account model / PDAs:** <PDAs, seeds, and on-chain state layout.>

**Rent & sizing:** <Account sizes, rent-exemption strategy, lamports budget.>

## Compute & Performance

**Compute budget:** <Expected compute units per instruction; ComputeBudget usage.>

**Fees:** <Priority fee / prioritization strategy.>

**Transaction reliability:** <Retries, blockhash expiry handling, commitment levels (processed/confirmed/finalized).>

## RPC & Infrastructure

**RPC provider:** <Helius / Triton / QuickNode / self-hosted, and why.>

**Rate limits & fallback:** <Throttling, backoff, failover endpoints.>

**Indexing / data access:** <Geyser, webhooks, DAS API, getProgramAccounts strategy.>

## Wallet & UX

**Wallet connection:** <Wallet adapter; supported wallets (Phantom, Solflare, Backpack).>

**Signing flows:** <How users sign / approve transactions.>

**Simulation & error states:** <Tx simulation, error handling, timeouts, user feedback.>

## Tokenomics / SPL

> Delete this section if your product has no token.

**Token standard:** <SPL Token or Token-2022; extensions used.>

**Supply / decimals / distribution:** <Total supply, decimals, allocation, vesting.>

**Authorities:** <Mint authority, freeze authority, and any revocation plan.>

## Security & Trust

**Upgrade authority / admin:** <Who controls upgrades? Multisig / governance / immutable?>

**Audit plan:** <Audit, internal review, or bug bounty.>

**Key management:** <KMS, hardware wallets, custody, signer separation.>

**Abuse / threat vectors:** <Phishing, drainers, sybil, MEV, replay, exploit surface.>

## Success Metrics

**KPIs:** <Name them: DAU, TVL, retention, conversion.>

**Targets (measurable):** <e.g. 1,000 DAU in 90 days; <2s median confirmation; >99% tx success.>

## Risks & Mitigations

| Risk | Likelihood | Impact | Mitigation |
| --- | --- | --- | --- |
| <risk> | <low/med/high> | <low/med/high> | <mitigation> |

## Milestones & Rollout

- **Phase 1 (localnet/devnet):** <scope + timing>
- **Phase 2 (testnet/audit):** <scope + timing>
- **Phase 3 (mainnet launch):** <scope + timing>

## Open Questions

- <unresolved question / decision to be made>
`;

const PRESETS = {
	default: { title: "Solana Product", body: BASE_TEMPLATE },
	defi: {
		title: "DeFi Protocol",
		body: BASE_TEMPLATE.replace("# <Project Name> — PRD", "# <Project Name> — DeFi PRD").replace("<feature 1>", "AMM / lending / staking pools").replace("<feature 2>", "Oracle price feeds (Pyth/Switchboard)"),
	},
	nft: {
		title: "NFT / Mint",
		body: BASE_TEMPLATE.replace("# <Project Name> — PRD", "# <Project Name> — NFT PRD").replace("<feature 1>", "Candy Machine / mint flow").replace("<feature 2>", "Metadata & royalties (Metaplex)"),
	},
	wallet: {
		title: "Wallet / Terminal",
		body: BASE_TEMPLATE.replace("# <Project Name> — PRD", "# <Project Name> — Wallet/Terminal PRD").replace("<feature 1>", "Portfolio & balances view").replace("<feature 2>", "Swap / send / receive flows"),
	},
	token_launch: {
		title: "Token Launch",
		body: BASE_TEMPLATE.replace("# <Project Name> — PRD", "# <Project Name> — Token Launch PRD").replace("<feature 1>", "Token creation + liquidity bootstrap").replace("<feature 2>", "Launch UX + anti-bot measures"),
	},
};

function getTemplate(preset) {
	const p = PRESETS[preset] || PRESETS.default;
	return p.body;
}

module.exports = { getTemplate, PRESETS, BASE_TEMPLATE };
